appraise 'rails-4.2' do
  source 'https://rubygems.org'
  gem 'rails', '4.2.9'
  gem 'devise'
  gem 'pg'
  gem 'redis'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'test_declarative'
  gem 'mocha'
  gem 'webmock'
  gem 'sass-rails'
  gem 'jquery-rails'
  gem 'coffee-rails'
  gem 'pry-rails'
end

appraise 'rails-5' do
  source 'https://rubygems.org'
  gem 'rails', '5.0.1'
  gem 'devise'
  gem 'pg'
  gem 'redis'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'test_declarative'
  gem 'mocha'
  gem 'webmock'
  gem 'sass-rails'
  gem 'jquery-rails'
  gem 'coffee-rails'
  gem 'pry-rails'
  gem 'rails-controller-testing'
  gem 'minitest', '~> 5.10', '> 5.10.2'
end
